# build environment
FROM node:lts-alpine3.14 as promise-client-build
WORKDIR /app
ENV PATH /app/node_modules/.bin:$PATH
COPY package.json yarn.lock ./
RUN rm -rf node_modules && yarn install --frozen-lockfile --silent
COPY . ./
RUN yarn build

# production environment
FROM nginx:stable-alpine
COPY --from=promise-client-build /app/build /usr/share/nginx/html
COPY nginx/nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]